server:
  port: 9191
  
spring:
  h2:
    console:
      enabled: true
  application:
    name: PaymentService     
eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true    